project:
  type: website
  output-dir: docs

website:
  title: "Bike_Share"
  navbar:
    left:
      - href: index.qmd
        text: BikeShare
#      - about.qmd

format:
  html:
    theme:
        light: flatly
        dark: darkly
    #sass: styles.sass
    toc: true
    page-layout: custom

editor: visual

