project:
  type: website
  output-dir: docs

website:
  title: "Bike_Share"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: bikeShare.qmd
        text: Bike Share

format:
  html:
    theme: solar
    sass: styles.sass
    toc: true

editor: visual

