project:
  type: website
  output-dir: docs
  image: "images/bikeSharePng.png"
  open-graph: true

  
execute: 
  cache: false
  freeze: auto

website:
  title: "BikeShare Analysis"
  open-graph: true
  image: "images/previewThumbnail.png"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

preview:
  browser: true

format:
  html:
    theme:
        - darkly
        - theme-dark.scss
    toc: false
    page-layout: article

editor: source
