project:
  type: website
  output-dir: docs

website:
  title: "BikeShare Analysis"
  #navbar:
   # left:
  #    - href: index.qmd
    #    text: BikeShare
#   #   - about.qmd

format:
  html:
    theme:
        light: flatly
        dark: darkly
    #sass: styles.sass
    toc: false
    page-layout: custom

editor: visual

