project:
  type: website
  output-dir: docs
  
execute: 
  cache: false
  freeze: auto

#execute: 
# freeze: auto

website:
  title: "BikeShare Analysis"
#  navbar:
#   left:
#      - href: index.qmd
#        text: BikeShare
#      - about.qmd

format:
  html:
    theme:
        - darkly
        - theme-dark.scss
    toc: false
    page-layout: article
    #include-in-header: themeToggle.html
    
editor: source