project:
  type: website
  output-dir: docs

#execute: 
# freeze: auto

website:
  title: "BikeShare Analysis"
  navbar:
    left:
      - href: index.qmd
    #    text: BikeShare
#   #   - about.qmd

format:
  html:
    theme:
        light: morph
        dark: [morph, custom-theme.sass]
    toc: false
    page-layout: custom
        

editor: visual

